### ISSUE TITLE
Git push error

### ISSUE THREAD

**Issue by 6ie** [kaardiminutid/kaardiminutid#11]
Esimese kohtumise kodutööd juhendi järgi tehes sain muudatusi tagasi pushides errori:
"remote: Permission to kaardiminutid/kaardiminutid.git denied to 6ie.
fatal: unable to access 'https://github.com/kaardiminutid/kaardiminutid.git/': The requested URL returned error: 403"

Sain probleemist jagu, kui kloonisin giti mustas aknas **enda** forki mitte **originali**.

Abi sain siit:
https://stackoverflow.com/questions/17857283/permission-denied-error-on-github-push

Toimis selline töövoog:
click fork button on original github project page
clone your forked repository instead original
push to it
press Pull Requests button on your repository
create it
wait for original author to accept it

**Comment by tkardi** [comment]
Aitäh, väga hea et tähele panid, teada andsid.
